/* eslint-disable */
/**
 * This file was automatically generated by @algorandfoundation/algokit-client-generator.
 * DO NOT MODIFY IT BY HAND.
 * requires: @algorandfoundation/algokit-utils: ^7
 */
import { type AlgorandClient } from '@algorandfoundation/algokit-utils/types/algorand-client'
import { ABIReturn, AppReturn, SendAppTransactionResult } from '@algorandfoundation/algokit-utils/types/app'
import { Arc56Contract, getArc56ReturnValue, getABIStructFromABITuple } from '@algorandfoundation/algokit-utils/types/app-arc56'
import {
  AppClient as _AppClient,
  AppClientMethodCallParams,
  AppClientParams,
  AppClientBareCallParams,
  CallOnComplete,
  AppClientCompilationParams,
  ResolveAppClientByCreatorAndName,
  ResolveAppClientByNetwork,
  CloneAppClientParams,
} from '@algorandfoundation/algokit-utils/types/app-client'
import { AppFactory as _AppFactory, AppFactoryAppClientParams, AppFactoryResolveAppClientByCreatorAndNameParams, AppFactoryDeployParams, AppFactoryParams, CreateSchema } from '@algorandfoundation/algokit-utils/types/app-factory'
import { TransactionComposer, AppCallMethodCall, AppMethodCallTransactionArgument, SimulateOptions, RawSimulateOptions, SkipSignaturesSimulateOptions } from '@algorandfoundation/algokit-utils/types/composer'
import { SendParams, SendSingleTransactionResult, SendAtomicTransactionComposerResults } from '@algorandfoundation/algokit-utils/types/transaction'
import { Address, encodeAddress, modelsv2, OnApplicationComplete, Transaction, TransactionSigner } from 'algosdk'

export const APP_SPEC: Arc56Contract = {
  "name": "AugurionMarketV4",
  "structs": {},
  "methods": [
    {
      "name": "create",
      "args": [],
      "returns": { "type": "void" },
      "actions": { "create": [], "call": ["NoOp"] },
      "readonly": false,
      "events": [],
      "recommendations": {}
    },
    {
      "name": "configure_market",
      "args": [
        { "type": "byte[]", "name": "outcomeRef" },
        { "type": "uint64", "name": "expiryRound" },
        { "type": "uint64", "name": "feeBps" }
      ],
      "returns": { "type": "string" },
      "actions": { "create": [], "call": ["NoOp"] },
      "readonly": false,
      "desc": "Configure the market metadata before opening.\nCan be called multiple times while PENDING to fix wording/refs.",
      "events": [],
      "recommendations": {}
    },
    {
      "name": "open_market",
      "args": [],
      "returns": { "type": "string" },
      "actions": { "create": [], "call": ["NoOp"] },
      "readonly": false,
      "events": [],
      "recommendations": {}
    },
    {
      "name": "freeze_market",
      "args": [],
      "returns": { "type": "string" },
      "actions": { "create": [], "call": ["NoOp"] },
      "readonly": false,
      "events": [],
      "recommendations": {}
    },
    {
      "name": "cancel_market",
      "args": [],
      "returns": { "type": "string" },
      "actions": { "create": [], "call": ["NoOp"] },
      "readonly": false,
      "events": [],
      "recommendations": {}
    },
    {
      "name": "bet_yes",
      "args": [{ "type": "uint64", "name": "amount" }],
      "returns": { "type": "string" },
      "actions": { "create": [], "call": ["NoOp"] },
      "readonly": false,
      "events": [],
      "recommendations": {}
    },
    {
      "name": "bet_no",
      "args": [{ "type": "uint64", "name": "amount" }],
      "returns": { "type": "string" },
      "actions": { "create": [], "call": ["NoOp"] },
      "readonly": false,
      "events": [],
      "recommendations": {}
    },
    {
      "name": "resolve_market",
      "args": [{ "type": "uint64", "name": "winningSide" }],
      "returns": { "type": "string" },
      "actions": { "create": [], "call": ["NoOp"] },
      "readonly": false,
      "desc": "Admin-as-oracle resolves the market.\nPrefer: freeze first, then resolve.",
      "events": [],
      "recommendations": {}
    },
    {
      "name": "claim_payout",
      "args": [],
      "returns": { "type": "string" },
      "actions": { "create": [], "call": ["NoOp"] },
      "readonly": false,
      "events": [],
      "recommendations": {}
    },
    {
      "name": "claim_refund",
      "args": [],
      "returns": { "type": "string" },
      "actions": { "create": [], "call": ["NoOp"] },
      "readonly": false,
      "desc": "If market is cancelled, users can refund their YES+NO bets (one-time).",
      "events": [],
      "recommendations": {}
    },
    {
      "name": "get_market_meta",
      "args": [],
      "returns": { "type": "string" },
      "actions": { "create": [], "call": ["NoOp"] },
      "readonly": false,
      "events": [],
      "recommendations": {}
    }
  ],
  "arcs": [22, 28],
  "desc": "AugurionMarketV2_1 (single-market, ALGO collateral, parimutuel pool)\n\nLifecycle (status):\n0 = PENDING   (configured but not open)\n1 = OPEN      (accept bets)\n2 = FROZEN    (no more bets; awaiting resolution)\n3 = RESOLVED  (winner set; claims allowed)\n4 = CANCELLED (refunds allowed)\n\nwinningSide:\n0 = NONE\n1 = YES\n2 = NO",
  "networks": {},
  "state": {
    "schema": {
      "global": { "ints": 8, "bytes": 2 },
      "local": { "ints": 0, "bytes": 0 }
    },
    "keys": {
      "global": {
        "status": { "keyType": "AVMString", "valueType": "AVMUint64", "key": "c3RhdHVz" },
        "admin": { "keyType": "AVMString", "valueType": "address", "key": "YWRtaW4=" },
        "outcomeRef": { "keyType": "AVMString", "valueType": "AVMBytes", "key": "b3V0Y29tZVJlZg==" },
        "expiryRound": { "keyType": "AVMString", "valueType": "AVMUint64", "key": "ZXhwaXJ5Um91bmQ=" },
        "yesTotal": { "keyType": "AVMString", "valueType": "AVMUint64", "key": "eWVzVG90YWw=" },
        "noTotal": { "keyType": "AVMString", "valueType": "AVMUint64", "key": "bm9Ub3RhbA==" },
        "totalBets": { "keyType": "AVMString", "valueType": "AVMUint64", "key": "dG90YWxCZXRz" },
        "feeBps": { "keyType": "AVMString", "valueType": "AVMUint64", "key": "ZmVlQnBz" },
        "winningSide": { "keyType": "AVMString", "valueType": "AVMUint64", "key": "d2lubmluZ1NpZGU=" },
        "claimVersion": { "keyType": "AVMString", "valueType": "AVMUint64", "key": "Y2xhaW1WZXJzaW9u" }
      },
      "local": {},
      "box": {}
    },
    "maps": {
      "global": {},
      "local": {},
      "box": {
        "yesBet": { "keyType": "address", "valueType": "uint64", "prefix": "eWVzOg==" },
        "noBet": { "keyType": "address", "valueType": "uint64", "prefix": "bm86" },
        "claimed": { "keyType": "address", "valueType": "uint64", "prefix": "Y2xhaW1lZDo=" },
        "refunded": { "keyType": "address", "valueType": "uint64", "prefix": "cmVmdW5kZWQ6" }
      }
    }
  },
  "bareActions": { "create": ["NoOp"], "call": [] },
  "sourceInfo": {
    "approval": { "sourceInfo": [], "pcOffsetMethod": "none" },
    "clear": { "sourceInfo": [], "pcOffsetMethod": "none" }
  },
  "source": {}
} as unknown as Arc56Contract;

// Type definitions for contract state
export interface GlobalState {
  status: bigint;
  admin: string;
  outcomeRef: Uint8Array;
  expiryRound: bigint;
  yesTotal: bigint;
  noTotal: bigint;
  totalBets: bigint;
  feeBps: bigint;
  winningSide: bigint;
  claimVersion: bigint;
}

// Method argument types
export interface ConfigureMarketArgs {
  outcomeRef: Uint8Array;
  expiryRound: bigint | number;
  feeBps: bigint | number;
}

export interface BetArgs {
  amount: bigint | number;
}

export interface ResolveMarketArgs {
  winningSide: bigint | number;
}

// Status enum for readability
export enum MarketStatus {
  PENDING = 0,
  OPEN = 1,
  FROZEN = 2,
  RESOLVED = 3,
  CANCELLED = 4
}

export enum WinningSide {
  NONE = 0,
  YES = 1,
  NO = 2
}

export { APP_SPEC as AugurionMarketV4Spec };
