UPDATE public.markets SET researched_outcome = v.o, researched_source = v.s
FROM (VALUES
  ('FIFAWC26WinnerSpain','YES','Spain beat Argentina 1-0 a.e.t. in the final — FIFA/AP'),
  ('FIFAWC26WinnerEurope','YES','Winner Spain (UEFA) — FIFA'),
  ('FIFAWC26WinnerSouthAmerica','NO','Winner Spain (UEFA); Argentina runner-up — FIFA'),
  ('FIFAWC26WinnerfromAfrica','NO','Winner Spain — FIFA'),
  ('FIFAWC26WinBrazil','NO','Brazil eliminated in Round of 16 by Norway (2-1) — ESPN'),
  ('FIFAWC26WinnerFrance','NO','France lost the third-place play-off to England 6-4 — ESPN'),
  ('FIFAWC26WinnerEngland','NO','England finished third — ESPN'),
  ('FIFAWC26WinnerGermany','NO','Germany out in Round of 32 on penalties to Paraguay — Sky/BBC'),
  ('FIFAWC26WinnerArgentina','NO','Argentina lost the final 0-1 to Spain — AP'),
  ('FIFAWC26FinalExtraTime','YES','Final decided by Ferran Torres in the 106th minute (extra time) — AP'),
  ('FIFAWC26FinalPenalties','NO','Final settled in extra time, no shootout — AP'),
  ('FIFAWC26SubstituteScoresInFinal','YES','Ferran Torres, on for Oyarzabal at 62'', scored the 106th-minute winner — AP'),
  ('FIFAWC26DefendingChampSemiFinals','YES','Defending champion Argentina reached the semi-finals and the final — BBC'),
  ('FIFAWC26DefendingChampFinal','YES','Argentina reached the final, losing 0-1 to Spain — AP'),
  ('FIFAWC26AfricanTeamReachesFinal','NO','Final was Spain vs Argentina — FIFA'),
  ('FIFAWC262PlusAfriTeamsSemiFinal','NO','Semi-finalists were Spain, Argentina, France, England — BBC'),
  ('FIFAWC26MarNgaEgyGhaSemi','NO','No African team reached the semi-finals; Morocco out in the quarter-finals — AP'),
  ('FIFAWC26AfricaTeamQuarterFinal','YES','Morocco reached the quarter-finals, losing 2-0 to France — AP'),
  ('FIFAWC26MoroccoFurthestAfrican','YES','Morocco (quarter-finals) went furthest of the African teams — AP/ESPN'),
  ('FIFAWC262AfricanTeamsRoundof32','YES','Nine of the ten African qualifiers reached the Round of 32 — Channels TV'),
  ('FIFAWC26NigeriaRoundof16','NO','Nigeria failed to qualify, losing the play-off to DR Congo on penalties — BBC'),
  ('FIFAWC26SenegalRoundof16','NO','Senegal eliminated in the Round of 32 by Belgium (2-3) — Al Jazeera'),
  ('FIFAWC26EgyptRoundof16','YES','Egypt reached the Round of 16 for the first time, losing 0-2 to Argentina — ESPN'),
  ('FIFAWC26SenegalDisqualified','NO','Senegal played the World Cup; the AFCON final fallout was a CAF matter (title awarded to Morocco) — AP/Reuters'),
  ('FIFAWC26TrumpBoycott6PlusCountries','NO','Calls for a boycott but no country withdrew; full participation — AP/Washington Post'),
  ('FIFAWC26SABeatsMexicoOpener','NO','Mexico beat South Africa 2-0 in the opener on 11 June 2026 — FIFA/AP'),
  ('FIFAWC26GoldenBootAfrica','NO','Golden Boot: Kylian Mbappé (France), 10 goals — FIFA'),
  ('FIFAWC26GoldenBootfromEU','YES','Golden Boot: Kylian Mbappé (France, Europe) — FIFA'),
  ('FIFAWC26GoldenBootSouthAmerica','NO','Golden Boot: Kylian Mbappé (France) — FIFA'),
  ('FIFAWC26GoldenBoot7PlusGoals','YES','Mbappé won the Golden Boot with 10 goals — FIFA'),
  ('FIFAWC26Mbappe5PlusGoals','YES','Mbappé scored 10 goals — FIFA'),
  ('FIFAWC26Messi2PlusGoals','YES','Messi scored 8 goals, including a hat-trick — AP/World Cup stats'),
  ('FIFAWC26Haaland5PlusGoals','YES','Haaland scored 7 goals, including a brace against Brazil — ESPN'),
  ('FIFAWC26TotalGoals170Plus','YES','308 goals scored in the 48-team tournament — FIFA'),
  ('FIFAWC26AnyGamewith6Goal','YES','England 6-4 France in the third-place play-off — ESPN/BBC'),
  ('FIFAWC26HatTrick2PlusPlayers','YES','Hat-tricks by Ousmane Dembélé (v Norway) and Lionel Messi — Al Jazeera/AP'),
  ('FIFAWC26PenaltyDecide1GameAtLeast','YES','Paraguay beat Germany 4-3 on penalties in the Round of 32 — BBC/Sky'),
  ('FIFAWC26VAROverturnsGoalKO','YES','Jonathan Tah''s extra-time goal for Germany v Paraguay disallowed by VAR — BBC'),
  ('FIFAWC26VAROverturnsPenalty','YES','Late VAR-awarded penalty for Belgium against Senegal in the Round of 32 — Al Jazeera'),
  ('FIFAWC26AfricanPlayerScoreGroupStage','YES','Nine African teams advanced from the group stage, scoring throughout — Channels TV')
) AS v(ref,o,s)
WHERE public.markets.outcome_ref = v.ref AND public.markets.resolved_outcome IS NULL;